book_lib/book_lib/urls.py
from django.contrib import admin
from django.urls import path
from books import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('add/', views.add, name='add'),
    path('delete/<int:book_id>/', views.delete, name='delete'),
    path('edit/<int:book_id>', views.edit, name='edit'),
]

book_lib/books/models.py
from django.db import models

class Book(models.Model):
    book = models.CharField(max_length=100, verbose_name="Название книги")
    title = models.CharField(max_length=100, verbose_name="Имя автора")
    date = models.DateField(verbose_name="Дата издания")

    def __str__(self):
        return self.book

book_lib/books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book','title','date']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}) 
        }

book_lib/books/views.py
from django.shortcuts import render, redirect
from .models import Book
from .forms import BookForm

def index(request):
    books = Book.objects.all()
    form = BookForm()
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'books/index.html', {'books': books, 'form': form})

def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = BookForm()
    return render(request, 'books/index.html', {'form': form})

def delete(request, book_id):
    Book.objects.filter(id=book_id).delete()
    return redirect('home')

def edit(request, book_id):
    book = Book.objects.get(id=book_id)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = BookForm(instance=book)
    return render(request, 'books/edit.html', {'form': form, 'book': book})

book_lib/book_lib/templates/books/index.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Список библиотек</title>
	</head>
	<body>
		<h1>Список книг</h1>
		<form action="/add/" method="post">
			{% csrf_token %}
			<label for="book">Книга:</label>
			<input type="text" id="book" name="book" required />
			<label for="date">Дата:</label>
			<input type="date" id="date" name="date" required />
			<button type="submit">Добавить книгу</button>
		</form>
		<ul>
			{% for book in books %}
			<li>
				{{ book.book }} : {{ book.date|date:"d.m.Y" }}
				<a href="{% url 'delete' book.pk %}">Удалить</a>
				<a href="{% url 'edit' book.pk %}">Изменить</a>
			</li>
			{% endfor %}
		</ul>
	</body>
</html>

book_lib/templates/books/edit.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Изменение данных</title>
	</head>
	<body>
		<h1>Изменение данных</h1>
		<form action="{% url 'edit' book.id %}" method="post">
			{% csrf_token %}
			<label for="id_book" required>Книга:</label>
			{{ form.book }}
			<label for="id_date">Дата:</label>
			{{ form.date }}
			<input type="submit" value="Сохранить" />
		</form>
	</body>
</html>

book_lib/templates/books/index.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Список библиотек</title>
	</head>
	<body>
		<h1>Список книг</h1>
		<form action="/add/" method="post">
			{% csrf_token %}
			<label for="book">Книга:</label>
			<input type="text" id="book" name="book" required />
			<label for="book">Автор:</label>
			<input type="text" id="book" name="book" required />
			<label for="date">Дата:</label>
			<input type="date" id="date" name="date" required />
			<button type="submit">Добавить книгу</button>
		</form>
		<ul>
			{% for book in books %}
			<li>
				{{ book.book }} : {{ book.date|date:"d.m.Y" }}
				<a href="{% url 'delete' book.pk %}">Удалить</a>
				<a href="{% url 'edit' book.pk %}">Изменить</a>
			</li>
			{% endfor %}
		</ul>
	</body>
</html>